name: Build and Deploy Hugo Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo site
      run: hugo --minify

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Update Kubernetes manifests
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        KOKKO_TOKEN: ${{ secrets.KOKKO_PAT }}
        NEW_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      run: |
        # Clone del repository dei manifest
        git clone https://${{ github.actor }}:${KOKKO_TOKEN}@github.com/nonzod/kokko.git /tmp/kokko
        cd /tmp/kokko
        
        # Configura Git
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        # Aggiorna l'immagine nel deployment
        sed -i "s|image: ghcr.io/nonzod/personal-website:.*|image: ${NEW_IMAGE}|" k8s/base/http/nicolatomassoni/deployment.yaml
        
        # Commit e push
        git add k8s/base/http/nicolatomassoni/deployment.yaml
        git commit -m "🚀 Update nicolatomassoni-website image to ${GITHUB_SHA::7}" || exit 0
        git push origin master